# Generated by Django 4.2.24 on 2025-12-10 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="#RRGGBB format", max_length=7, null=True
                    ),
                ),
                (
                    "color_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior Color"),
                            ("interior", "Interior Color"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Color swatch/preview",
                        null=True,
                        upload_to="car_colors/",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Car Color",
                "verbose_name_plural": "Car Colors",
                "ordering": ["color_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ElectricCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Long Range, Performance, Standard",
                        max_length=100,
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2008),
                            django.core.validators.MaxValueValidator(2025),
                        ]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("crossover", "Crossover"),
                            ("hatchback", "Hatchback"),
                            ("coupe", "Coupe"),
                            ("convertible", "Convertible"),
                            ("sports", "Sports Car"),
                            ("pickup", "Pickup Truck"),
                            ("van", "Van/Minibus"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available for Sale"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("test_drive", "Available for Test Drive"),
                            ("coming_soon", "Coming Soon"),
                            ("pre_order", "Pre-order Available"),
                            ("display", "Display Model Only"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured on homepage"
                    ),
                ),
                (
                    "battery_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total battery capacity in kWh",
                        max_digits=6,
                    ),
                ),
                (
                    "usable_battery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usable battery capacity in kWh",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "battery_type",
                    models.CharField(
                        choices=[
                            ("lithium_ion", "Lithium-Ion"),
                            ("lithium_polymer", "Lithium Polymer"),
                            ("solid_state", "Solid State"),
                            ("lifepo4", "Lithium Iron Phosphate (LiFePO4)"),
                            ("nmc", "NMC (Nickel Manganese Cobalt)"),
                            ("lto", "LTO (Lithium Titanate)"),
                        ],
                        default="lithium_ion",
                        max_length=20,
                    ),
                ),
                ("battery_warranty_years", models.IntegerField(default=8)),
                (
                    "battery_warranty_km",
                    models.IntegerField(
                        default=160000, help_text="Warranty in kilometers"
                    ),
                ),
                (
                    "range_wltp",
                    models.IntegerField(
                        help_text="WLTP range in km", verbose_name="WLTP Range"
                    ),
                ),
                (
                    "range_epa",
                    models.IntegerField(
                        blank=True,
                        help_text="EPA estimated range in km",
                        null=True,
                        verbose_name="EPA Range",
                    ),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Energy consumption in kWh/100km",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "acceleration_0_100",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="0-100 km/h acceleration in seconds",
                        max_digits=3,
                    ),
                ),
                ("top_speed", models.IntegerField(help_text="Top speed in km/h")),
                (
                    "motor_power",
                    models.IntegerField(help_text="Total motor power in kW"),
                ),
                ("torque", models.IntegerField(help_text="Torque in Nm")),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("rwd", "Rear Wheel Drive"),
                            ("fwd", "Front Wheel Drive"),
                            ("awd", "All Wheel Drive"),
                            ("dual_motor", "Dual Motor AWD"),
                            ("tri_motor", "Tri Motor AWD"),
                            ("quad_motor", "Quad Motor AWD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_dc_charging",
                    models.IntegerField(
                        help_text="Maximum DC charging power in kW",
                        verbose_name="Max DC Charging",
                    ),
                ),
                (
                    "max_ac_charging",
                    models.IntegerField(
                        help_text="Maximum AC charging power in kW",
                        verbose_name="Max AC Charging",
                    ),
                ),
                (
                    "charging_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1 (SAE J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs1", "CCS1 (Combo 1)"),
                            ("ccs2", "CCS2 (Combo 2)"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla Supercharger"),
                            ("gb_t", "GB/T (China)"),
                            ("nacs", "NACS (Tesla Standard)"),
                        ],
                        default="ccs2",
                        max_length=20,
                    ),
                ),
                (
                    "charging_time_10_80",
                    models.IntegerField(
                        help_text="Time to charge from 10% to 80% at max DC power (minutes)"
                    ),
                ),
                (
                    "charging_time_0_100_ac",
                    models.IntegerField(
                        blank=True,
                        help_text="Time for 0-100% on 11kW AC charger (hours)",
                        null=True,
                    ),
                ),
                ("length", models.IntegerField(help_text="Length in mm")),
                ("width", models.IntegerField(help_text="Width in mm")),
                ("height", models.IntegerField(help_text="Height in mm")),
                (
                    "wheelbase",
                    models.IntegerField(
                        blank=True, help_text="Wheelbase in mm", null=True
                    ),
                ),
                ("curb_weight", models.IntegerField(help_text="Curb weight in kg")),
                (
                    "cargo_capacity",
                    models.IntegerField(help_text="Cargo capacity in liters"),
                ),
                ("seating_capacity", models.IntegerField(default=5)),
                ("has_heat_pump", models.BooleanField(default=False)),
                ("has_battery_preconditioning", models.BooleanField(default=False)),
                (
                    "has_v2l",
                    models.BooleanField(
                        default=False,
                        help_text="Can power external devices",
                        verbose_name="Vehicle-to-Load",
                    ),
                ),
                (
                    "has_v2g",
                    models.BooleanField(
                        default=False,
                        help_text="Can supply power back to grid",
                        verbose_name="Vehicle-to-Grid",
                    ),
                ),
                ("has_one_pedal_driving", models.BooleanField(default=False)),
                (
                    "regen_braking_levels",
                    models.IntegerField(
                        default=1, help_text="Number of regenerative braking levels"
                    ),
                ),
                (
                    "autopilot_level",
                    models.CharField(
                        choices=[
                            ("none", "No Autopilot"),
                            ("basic", "Basic Driver Assistance"),
                            ("level2", "Level 2 Autonomy"),
                            ("level3", "Level 3 Autonomy"),
                            ("level4", "Level 4 Autonomy"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "charging_port_location",
                    models.CharField(
                        choices=[
                            ("front_left", "Front Left"),
                            ("front_right", "Front Right"),
                            ("rear_left", "Rear Left"),
                            ("rear_right", "Rear Right"),
                            ("front", "Front Center"),
                            ("rear", "Rear Center"),
                        ],
                        default="rear_left",
                        max_length=50,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price in ETB", max_digits=12
                    ),
                ),
                (
                    "estimated_delivery",
                    models.CharField(
                        blank=True, help_text="Estimated delivery time", max_length=100
                    ),
                ),
                (
                    "tax_incentive",
                    models.BooleanField(
                        default=False,
                        help_text="Eligible for government tax incentives",
                    ),
                ),
                ("main_image", models.ImageField(upload_to="electric_cars/main/")),
                (
                    "brochure",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="electric_cars/brochures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "key_features",
                    models.TextField(help_text="List key features separated by commas"),
                ),
                (
                    "safety_features",
                    models.TextField(blank=True, help_text="Safety features"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "available_exterior_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Available exterior color options",
                        limit_choices_to={"color_type": "exterior"},
                        related_name="available_exterior_cars",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "available_interior_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Available interior color options",
                        limit_choices_to={"color_type": "interior"},
                        related_name="available_interior_cars",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electric Car",
                "verbose_name_plural": "Electric Cars",
                "ordering": ["manufacturer", "model_name", "model_year"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "is_ev_only",
                    models.BooleanField(
                        default=False, verbose_name="EV Only Manufacturer"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="manufacturer_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EVReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("pros", models.TextField(help_text="Separate pros with commas")),
                ("cons", models.TextField(help_text="Separate cons with commas")),
                ("verified_owner", models.BooleanField(default=False)),
                ("review_date", models.DateField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={"ordering": ["-review_date"],},
        ),
        migrations.CreateModel(
            name="EVComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cars",
                    models.ManyToManyField(
                        related_name="comparisons", to="etop_backend.electriccar"
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AddField(
            model_name="electriccar",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electric_cars",
                to="etop_backend.manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="ChargingSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_dc_port", models.BooleanField(default=True)),
                ("has_ac_port", models.BooleanField(default=True)),
                (
                    "time_10_80_dc",
                    models.IntegerField(
                        help_text="Minutes for 10-80% on DC fast charger"
                    ),
                ),
                (
                    "time_0_100_ac_11kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 11kW AC charger",
                        null=True,
                    ),
                ),
                (
                    "time_0_100_ac_7kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 7kW AC charger",
                        null=True,
                    ),
                ),
                ("battery_warranty_years", models.IntegerField(default=8)),
                ("battery_warranty_miles", models.IntegerField(default=100000)),
                (
                    "battery_thermal_management",
                    models.CharField(
                        choices=[
                            ("liquid", "Liquid Cooling"),
                            ("air", "Air Cooling"),
                            ("passive", "Passive Cooling"),
                            ("hybrid", "Hybrid Cooling"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charging_specs",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Specification",
                "verbose_name_plural": "Charging Specifications",
            },
        ),
        migrations.AlterUniqueTogether(
            name="electriccar",
            unique_together={("manufacturer", "model_name", "variant", "model_year")},
        ),
        migrations.CreateModel(
            name="CarColorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_color_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior View"),
                            ("interior", "Interior View"),
                            ("angle", "Angle View"),
                            ("detail", "Detail Shot"),
                            ("color_swatch", "Color Swatch"),
                        ],
                        default="exterior",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image for this color combination",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order for display"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_images",
                        to="etop_backend.electriccar",
                    ),
                ),
                (
                    "exterior_color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"color_type": "exterior"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exterior_car_images",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "interior_color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"color_type": "interior"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interior_car_images",
                        to="etop_backend.carcolor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Color Image",
                "verbose_name_plural": "Car Color Images",
                "ordering": ["order", "-is_primary"],
                "unique_together": {
                    ("car", "exterior_color", "interior_color", "image_type")
                },
            },
        ),
        migrations.CreateModel(
            name="CarColorConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional cost for this color combination (can be negative)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Popular color combination"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "delivery_time",
                    models.CharField(
                        blank=True,
                        help_text="Special delivery time for this combination",
                        max_length=50,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_configurations",
                        to="etop_backend.electriccar",
                    ),
                ),
                (
                    "exterior_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "exterior"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exterior_configurations",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "interior_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "interior"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interior_configurations",
                        to="etop_backend.carcolor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Color Configuration",
                "verbose_name_plural": "Car Color Configurations",
                "ordering": ["-is_popular", "price_adjustment"],
                "unique_together": {("car", "exterior_color", "interior_color")},
            },
        ),
    ]
