# Generated by Django 4.2.27 on 2025-12-23 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etop_backend.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="#RRGGBB format", max_length=7, null=True
                    ),
                ),
                (
                    "color_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior Color"),
                            ("interior", "Interior Color"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Color swatch/preview",
                        null=True,
                        upload_to="car_colors/",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Car Color",
                "verbose_name_plural": "Car Colors",
                "ordering": ["color_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("custom_make", models.CharField(blank=True, max_length=100)),
                ("custom_model", models.CharField(blank=True, max_length=100)),
                (
                    "custom_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                ("license_plate", models.CharField(max_length=20)),
                (
                    "vin",
                    models.CharField(
                        max_length=17, verbose_name="Vehicle Identification Number"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("our_dealership", "Purchased from Our Dealership"),
                            ("other_dealership", "Purchased from Other Dealership"),
                            ("private_sale", "Private Sale"),
                            ("company_fleet", "Company Fleet"),
                            ("rental", "Rental Vehicle"),
                            ("other", "Other"),
                        ],
                        default="our_dealership",
                        max_length=20,
                    ),
                ),
                ("purchased_from_us", models.BooleanField(default=False)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_odometer",
                    models.IntegerField(
                        blank=True,
                        help_text="Odometer reading at purchase (km)",
                        null=True,
                    ),
                ),
                ("sales_invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "current_odometer",
                    models.IntegerField(
                        help_text="Current odometer reading in kilometers"
                    ),
                ),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("last_service_odometer", models.IntegerField(blank=True, null=True)),
                ("last_service_type", models.CharField(blank=True, max_length=100)),
                ("has_warranty", models.BooleanField(default=False)),
                ("warranty_start_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("warranty_type", models.CharField(blank=True, max_length=100)),
                ("warranty_terms", models.TextField(blank=True)),
                ("is_neta_car", models.BooleanField(default=False)),
                (
                    "neta_battery_warranty_years",
                    models.IntegerField(
                        default=2, help_text="NETA battery warranty years"
                    ),
                ),
                (
                    "neta_battery_warranty_km",
                    models.IntegerField(
                        default=50000, help_text="NETA battery warranty kilometers"
                    ),
                ),
                ("is_eligible_for_10000km_service", models.BooleanField(default=False)),
                (
                    "next_service_due_km",
                    models.IntegerField(
                        blank=True,
                        help_text="Next service due at this kilometer reading",
                        null=True,
                    ),
                ),
                (
                    "next_service_due_date",
                    models.DateField(
                        blank=True, help_text="Next service due date", null=True
                    ),
                ),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Vehicle",
                "verbose_name_plural": "Customer Vehicles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ElectricCar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "variant",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Long Range, Performance, Standard",
                        max_length=100,
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2008),
                            django.core.validators.MaxValueValidator(2025),
                        ]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("suv", "SUV"),
                            ("crossover", "Crossover"),
                            ("hatchback", "Hatchback"),
                            ("coupe", "Coupe"),
                            ("convertible", "Convertible"),
                            ("sports", "Sports Car"),
                            ("pickup", "Pickup Truck"),
                            ("van", "Van/Minibus"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available for Sale"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("test_drive", "Available for Test Drive"),
                            ("coming_soon", "Coming Soon"),
                            ("pre_order", "Pre-order Available"),
                            ("display", "Display Model Only"),
                        ],
                        default="available",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Featured on homepage",
                        null=True,
                    ),
                ),
                (
                    "battery_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total battery capacity in kWh",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "usable_battery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usable battery capacity in kWh",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "battery_type",
                    models.CharField(
                        choices=[
                            ("lithium_ion", "Lithium-Ion"),
                            ("lithium_polymer", "Lithium Polymer"),
                            ("solid_state", "Solid State"),
                            ("lifepo4", "Lithium Iron Phosphate (LiFePO4)"),
                            ("nmc", "NMC (Nickel Manganese Cobalt)"),
                            ("lto", "LTO (Lithium Titanate)"),
                        ],
                        default="lithium_ion",
                        max_length=20,
                    ),
                ),
                (
                    "battery_warranty_years",
                    models.IntegerField(blank=True, default=8, null=True),
                ),
                (
                    "battery_warranty_km",
                    models.IntegerField(
                        blank=True,
                        default=160000,
                        help_text="Warranty in kilometers",
                        null=True,
                    ),
                ),
                (
                    "range_wltp",
                    models.IntegerField(
                        blank=True,
                        help_text="WLTP range in km",
                        null=True,
                        verbose_name="WLTP Range",
                    ),
                ),
                (
                    "range_epa",
                    models.IntegerField(
                        blank=True,
                        help_text="EPA estimated range in km",
                        null=True,
                        verbose_name="EPA Range",
                    ),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Energy consumption in kWh/100km",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "acceleration_0_100",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="0-100 km/h acceleration in seconds",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "top_speed",
                    models.IntegerField(
                        blank=True, help_text="Top speed in km/h", null=True
                    ),
                ),
                (
                    "motor_power",
                    models.IntegerField(
                        blank=True, help_text="Total motor power in kW", null=True
                    ),
                ),
                (
                    "torque",
                    models.IntegerField(
                        blank=True, help_text="Torque in Nm", null=True
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rwd", "Rear Wheel Drive"),
                            ("fwd", "Front Wheel Drive"),
                            ("awd", "All Wheel Drive"),
                            ("dual_motor", "Dual Motor AWD"),
                            ("tri_motor", "Tri Motor AWD"),
                            ("quad_motor", "Quad Motor AWD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "max_dc_charging",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum DC charging power in kW",
                        null=True,
                        verbose_name="Max DC Charging",
                    ),
                ),
                (
                    "max_ac_charging",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum AC charging power in kW",
                        null=True,
                        verbose_name="Max AC Charging",
                    ),
                ),
                (
                    "charging_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("type1", "Type 1 (SAE J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs1", "CCS1 (Combo 1)"),
                            ("ccs2", "CCS2 (Combo 2)"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla Supercharger"),
                            ("gb_t", "GB/T (China)"),
                            ("nacs", "NACS (Tesla Standard)"),
                        ],
                        default="ccs2",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "charging_time_10_80",
                    models.IntegerField(
                        blank=True,
                        help_text="Time to charge from 10% to 80% at max DC power (minutes)",
                        null=True,
                    ),
                ),
                (
                    "charging_time_0_100_ac",
                    models.IntegerField(
                        blank=True,
                        help_text="Time for 0-100% on 11kW AC charger (hours)",
                        null=True,
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        blank=True, help_text="Length in mm", null=True
                    ),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, help_text="Width in mm", null=True),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Height in mm", null=True
                    ),
                ),
                (
                    "wheelbase",
                    models.IntegerField(
                        blank=True, help_text="Wheelbase in mm", null=True
                    ),
                ),
                (
                    "curb_weight",
                    models.IntegerField(
                        blank=True, help_text="Curb weight in kg", null=True
                    ),
                ),
                (
                    "cargo_capacity",
                    models.IntegerField(
                        blank=True, help_text="Cargo capacity in liters", null=True
                    ),
                ),
                (
                    "seating_capacity",
                    models.IntegerField(blank=True, default=5, null=True),
                ),
                ("has_heat_pump", models.BooleanField(default=False)),
                ("has_battery_preconditioning", models.BooleanField(default=False)),
                (
                    "has_v2l",
                    models.BooleanField(
                        default=False,
                        help_text="Can power external devices",
                        verbose_name="Vehicle-to-Load",
                    ),
                ),
                (
                    "has_v2g",
                    models.BooleanField(
                        default=False,
                        help_text="Can supply power back to grid",
                        verbose_name="Vehicle-to-Grid",
                    ),
                ),
                ("has_one_pedal_driving", models.BooleanField(default=False)),
                (
                    "regen_braking_levels",
                    models.IntegerField(
                        default=1, help_text="Number of regenerative braking levels"
                    ),
                ),
                (
                    "autopilot_level",
                    models.CharField(
                        choices=[
                            ("none", "No Autopilot"),
                            ("basic", "Basic Driver Assistance"),
                            ("level2", "Level 2 Autonomy"),
                            ("level3", "Level 3 Autonomy"),
                            ("level4", "Level 4 Autonomy"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "charging_port_location",
                    models.CharField(
                        choices=[
                            ("front_left", "Front Left"),
                            ("front_right", "Front Right"),
                            ("rear_left", "Rear Left"),
                            ("rear_right", "Rear Right"),
                            ("front", "Front Center"),
                            ("rear", "Rear Center"),
                        ],
                        default="rear_left",
                        max_length=50,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price in ETB", max_digits=12
                    ),
                ),
                (
                    "estimated_delivery",
                    models.CharField(
                        blank=True, help_text="Estimated delivery time", max_length=100
                    ),
                ),
                (
                    "tax_incentive",
                    models.BooleanField(
                        default=False,
                        help_text="Eligible for government tax incentives",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="electric_cars/main/"
                    ),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="electric_cars/brochures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "key_features",
                    models.TextField(
                        blank=True,
                        help_text="List key features separated by commas",
                        null=True,
                    ),
                ),
                (
                    "safety_features",
                    models.TextField(blank=True, help_text="Safety features"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "available_exterior_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Available exterior color options",
                        limit_choices_to={"color_type": "exterior"},
                        related_name="available_exterior_cars",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "available_interior_colors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Available interior color options",
                        limit_choices_to={"color_type": "interior"},
                        related_name="available_interior_cars",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electric Car",
                "verbose_name_plural": "Electric Cars",
                "ordering": ["manufacturer", "model_name", "model_year"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "is_ev_only",
                    models.BooleanField(
                        default=False, verbose_name="EV Only Manufacturer"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="manufacturer_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming_service", "Upcoming Service"),
                            ("warranty_expiry", "Warranty Expiry"),
                            ("regular_maintenance", "Regular Maintenance"),
                            ("recall_notice", "Recall Notice"),
                            ("promotional", "Promotional Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reminder_date", models.DateField()),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_send_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="etop_backend.customervehicle",
                    ),
                ),
            ],
            options={"ordering": ["scheduled_send_date"],},
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        default=etop_backend.models.generate_booking_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        help_text="Full name of the customer", max_length=255
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Email address of the customer", max_length=255
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the customer",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("neta_warranty", "NETA 2-Year Warranty Service"),
                            ("10000km_service", "10,000 KM Service"),
                        ],
                        default="routine_maintenance",
                        max_length=50,
                    ),
                ),
                (
                    "service_type_custom",
                    models.CharField(
                        blank=True,
                        help_text="Custom service type if 'other' is selected",
                        max_length=100,
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time_slot", models.TimeField()),
                (
                    "alternative_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of alternative dates in YYYY-MM-DD format",
                    ),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this service has been scheduled via ScheduleService",
                    ),
                ),
                (
                    "odometer_reading",
                    models.IntegerField(
                        help_text="Current odometer reading at time of booking"
                    ),
                ),
                (
                    "service_description",
                    models.TextField(
                        blank=True, help_text="Detailed description of service needed"
                    ),
                ),
                (
                    "symptoms_problems",
                    models.TextField(
                        blank=True, help_text="Describe any symptoms or problems"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                            ("warranty", "Warranty Claim"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_odometer", models.IntegerField(blank=True, null=True)),
                ("service_report", models.TextField(blank=True)),
                (
                    "parts_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of parts used with IDs and quantities",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("warranty_covered", models.BooleanField(default=False)),
                ("warranty_claim_number", models.CharField(blank=True, max_length=50)),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("follow_up_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Technicians"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to specific service from company app",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="company.service",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="company.servicecenter",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Booking",
                "verbose_name_plural": "Service Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bookings",
                    models.ManyToManyField(
                        related_name="schedules", to="etop_backend.servicebooking"
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.servicecenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Service",
                "verbose_name_plural": "Scheduled Services",
            },
        ),
        migrations.CreateModel(
            name="EVReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("pros", models.TextField(help_text="Separate pros with commas")),
                ("cons", models.TextField(help_text="Separate cons with commas")),
                ("verified_owner", models.BooleanField(default=False)),
                ("review_date", models.DateField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={"ordering": ["-review_date"],},
        ),
        migrations.CreateModel(
            name="EVComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cars",
                    models.ManyToManyField(
                        related_name="comparisons", to="etop_backend.electriccar"
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Subscriber's email address",
                        max_length=255,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complaint", "Marked as Spam"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Subscription Status",
                    ),
                ),
                (
                    "receive_inventory_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Send emails when new inventory is added",
                        verbose_name="Receive Inventory Alerts",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscription Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Unsubscribed Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Admin Notes")),
                (
                    "sales_associate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select sales associate if customer was referred by one",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_subscribers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sales Associate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Subscriber",
                "verbose_name_plural": "Email Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.AddField(
            model_name="electriccar",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electric_cars",
                to="etop_backend.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="electric_car",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is one of our electric car models",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_vehicles",
                to="etop_backend.electriccar",
            ),
        ),
        migrations.CreateModel(
            name="ContactOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField(help_text="Message sent by the customer")),
                (
                    "preferred_contact_time",
                    models.CharField(
                        choices=[
                            ("6h", "Within 6 hours"),
                            ("24h", "Within 24 hours"),
                            ("48h", "Within 48 hours"),
                        ],
                        default="24h",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "electric_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_orders",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Order",
                "verbose_name_plural": "Contact Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChargingSpecification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_dc_port", models.BooleanField(default=True)),
                ("has_ac_port", models.BooleanField(default=True)),
                (
                    "time_10_80_dc",
                    models.IntegerField(
                        help_text="Minutes for 10-80% on DC fast charger"
                    ),
                ),
                (
                    "time_0_100_ac_11kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 11kW AC charger",
                        null=True,
                    ),
                ),
                (
                    "time_0_100_ac_7kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 7kW AC charger",
                        null=True,
                    ),
                ),
                ("battery_warranty_years", models.IntegerField(default=8)),
                ("battery_warranty_miles", models.IntegerField(default=100000)),
                (
                    "battery_thermal_management",
                    models.CharField(
                        choices=[
                            ("liquid", "Liquid Cooling"),
                            ("air", "Air Cooling"),
                            ("passive", "Passive Cooling"),
                            ("hybrid", "Hybrid Cooling"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charging_specs",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Specification",
                "verbose_name_plural": "Charging Specifications",
            },
        ),
        migrations.CreateModel(
            name="CarColorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="car_color_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior View"),
                            ("interior", "Interior View"),
                            ("angle", "Angle View"),
                            ("detail", "Detail Shot"),
                            ("color_swatch", "Color Swatch"),
                        ],
                        default="exterior",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary image for this color combination",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Order for display"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_images",
                        to="etop_backend.electriccar",
                    ),
                ),
                (
                    "exterior_color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"color_type": "exterior"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exterior_car_images",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "interior_color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"color_type": "interior"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interior_car_images",
                        to="etop_backend.carcolor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Color Image",
                "verbose_name_plural": "Car Color Images",
                "ordering": ["order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="CarColorConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional cost for this color combination (can be negative)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Popular color combination"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "delivery_time",
                    models.CharField(
                        blank=True,
                        help_text="Special delivery time for this combination",
                        max_length=50,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_configurations",
                        to="etop_backend.electriccar",
                    ),
                ),
                (
                    "exterior_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "exterior"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exterior_configurations",
                        to="etop_backend.carcolor",
                    ),
                ),
                (
                    "interior_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "interior"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interior_configurations",
                        to="etop_backend.carcolor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Color Configuration",
                "verbose_name_plural": "Car Color Configurations",
                "ordering": ["-is_popular", "price_adjustment"],
            },
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["booking_number"], name="etop_backen_booking_e88e01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(fields=["status"], name="etop_backen_status_e3a025_idx"),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["is_scheduled"], name="etop_backen_is_sche_1b38d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["customer"], name="etop_backen_custome_899d05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["preferred_date"], name="etop_backen_preferr_6027b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(fields=["email"], name="etop_backen_email_710c1a_idx"),
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(
                fields=["subscription_status"], name="etop_backen_subscri_f31904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(
                fields=["subscribed_at"], name="etop_backen_subscri_fd787a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(
                fields=["sales_associate"], name="etop_backen_sales_a_b0b9eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="electriccar",
            unique_together={("manufacturer", "model_name", "variant", "model_year")},
        ),
        migrations.AlterUniqueTogether(
            name="customervehicle", unique_together={("license_plate", "vin")},
        ),
        migrations.AlterUniqueTogether(
            name="carcolorimage",
            unique_together={("car", "exterior_color", "interior_color", "image_type")},
        ),
        migrations.AlterUniqueTogether(
            name="carcolorconfiguration",
            unique_together={("car", "exterior_color", "interior_color")},
        ),
    ]
