# Generated by Django 4.2.24 on 2025-12-10 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("variant", models.CharField(blank=True, max_length=100)),
                (
                    "model_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2008),
                            django.core.validators.MaxValueValidator(2025),
                        ]
                    ),
                ),
                (
                    "battery_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Battery capacity in kWh",
                        max_digits=6,
                    ),
                ),
                (
                    "battery_type",
                    models.CharField(
                        choices=[
                            ("lithium_ion", "Lithium-Ion"),
                            ("lithium_polymer", "Lithium Polymer"),
                            ("solid_state", "Solid State"),
                            ("lifepo4", "Lithium Iron Phosphate (LiFePO4)"),
                        ],
                        default="lithium_ion",
                        max_length=20,
                    ),
                ),
                (
                    "usable_battery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Usable battery capacity in kWh",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "range_epa",
                    models.IntegerField(
                        blank=True, help_text="EPA estimated range in miles", null=True
                    ),
                ),
                (
                    "range_wltp",
                    models.IntegerField(
                        blank=True, help_text="WLTP estimated range in miles", null=True
                    ),
                ),
                (
                    "acceleration_0_60",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="0-60 mph acceleration in seconds",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "top_speed",
                    models.IntegerField(
                        blank=True, help_text="Top speed in mph", null=True
                    ),
                ),
                ("fast_charging_support", models.BooleanField(default=True)),
                (
                    "max_dc_charging_power",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum DC charging power in kW",
                        null=True,
                    ),
                ),
                (
                    "max_ac_charging_power",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum AC charging power in kW",
                        null=True,
                    ),
                ),
                (
                    "charging_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1 (SAE J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs1", "CCS1 (Combo 1)"),
                            ("ccs2", "CCS2 (Combo 2)"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla Supercharger"),
                            ("gb_t", "GB/T (China)"),
                        ],
                        default="ccs1",
                        max_length=20,
                    ),
                ),
                (
                    "charging_time_10_80",
                    models.IntegerField(
                        blank=True,
                        help_text="Time to charge from 10% to 80% at max DC power (minutes)",
                        null=True,
                    ),
                ),
                ("motor_power", models.IntegerField(help_text="Motor power in kW")),
                (
                    "torque",
                    models.IntegerField(
                        blank=True, help_text="Torque in Nm", null=True
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("rwd", "Rear Wheel Drive"),
                            ("fwd", "Front Wheel Drive"),
                            ("awd", "All Wheel Drive"),
                            ("dual_motor", "Dual Motor AWD"),
                            ("tri_motor", "Tri Motor AWD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Length in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Width in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Height in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "curb_weight",
                    models.IntegerField(
                        blank=True, help_text="Curb weight in kg", null=True
                    ),
                ),
                (
                    "frunk_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Front trunk capacity in liters",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "trunk_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Rear trunk capacity in liters",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("has_heat_pump", models.BooleanField(default=False)),
                ("has_battery_preconditioning", models.BooleanField(default=False)),
                (
                    "has_v2l",
                    models.BooleanField(
                        default=False, help_text="Vehicle-to-Load capability"
                    ),
                ),
                (
                    "has_v2g",
                    models.BooleanField(
                        default=False, help_text="Vehicle-to-Grid capability"
                    ),
                ),
                ("has_one_pedal_driving", models.BooleanField(default=False)),
                (
                    "regen_braking_levels",
                    models.IntegerField(
                        default=1, help_text="Number of regenerative braking levels"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base price in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("eligible_for_tax_credit", models.BooleanField(default=False)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "production_status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("pre_order", "Pre-order"),
                            ("production", "In Production"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="production",
                        max_length=20,
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="ev_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Electric Car",
                "verbose_name_plural": "Electric Cars",
                "ordering": ["manufacturer", "model_name", "model_year"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("is_ev_only", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="EVReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("pros", models.TextField(help_text="Separate pros with commas")),
                ("cons", models.TextField(help_text="Separate cons with commas")),
                ("verified_owner", models.BooleanField(default=False)),
                ("review_date", models.DateField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={"ordering": ["-review_date"],},
        ),
        migrations.CreateModel(
            name="EVComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cars",
                    models.ManyToManyField(
                        related_name="comparisons", to="etop_backend.electriccar"
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AddField(
            model_name="electriccar",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electric_cars",
                to="etop_backend.manufacturer",
            ),
        ),
        migrations.CreateModel(
            name="ChargingSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_dc_port", models.BooleanField(default=True)),
                ("has_ac_port", models.BooleanField(default=True)),
                (
                    "time_10_80_dc",
                    models.IntegerField(
                        help_text="Minutes for 10-80% on DC fast charger"
                    ),
                ),
                (
                    "time_0_100_ac_11kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 11kW AC charger",
                        null=True,
                    ),
                ),
                (
                    "time_0_100_ac_7kw",
                    models.IntegerField(
                        blank=True,
                        help_text="Hours for 0-100% on 7kW AC charger",
                        null=True,
                    ),
                ),
                ("battery_warranty_years", models.IntegerField(default=8)),
                ("battery_warranty_miles", models.IntegerField(default=100000)),
                (
                    "battery_thermal_management",
                    models.CharField(
                        choices=[
                            ("liquid", "Liquid Cooling"),
                            ("air", "Air Cooling"),
                            ("passive", "Passive Cooling"),
                            ("hybrid", "Hybrid Cooling"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charging_specs",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Specification",
                "verbose_name_plural": "Charging Specifications",
            },
        ),
        migrations.AlterUniqueTogether(
            name="electriccar",
            unique_together={("manufacturer", "model_name", "variant", "model_year")},
        ),
    ]
