# Generated by Django 4.2.24 on 2025-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electriccar",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="electric_cars/main/"
            ),
        ),
    ]
