# Generated by Django 4.2.24 on 2025-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hex_code", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "color_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior Color"),
                            ("interior", "Interior Color"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="electriccar",
            name="exterior_colors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"color_type": "exterior"},
                related_name="exterior_cars",
                to="etop_backend.carcolor",
            ),
        ),
        migrations.AddField(
            model_name="electriccar",
            name="interior_colors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"color_type": "interior"},
                related_name="interior_cars",
                to="etop_backend.carcolor",
            ),
        ),
    ]
