# Generated by Django 4.2.27 on 2025-12-14 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etop_backend", "0002_alter_electriccar_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Subscriber's email address",
                        max_length=255,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complaint", "Marked as Spam"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Subscription Status",
                    ),
                ),
                (
                    "receive_inventory_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Send emails when new inventory is added",
                        verbose_name="Receive Inventory Alerts",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscription Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Unsubscribed Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Admin Notes")),
                (
                    "sales_associate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select sales associate if customer was referred by one",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_subscribers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sales Associate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Subscriber",
                "verbose_name_plural": "Email Subscribers",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(fields=["email"], name="etop_backen_email_710c1a_idx"),
                    models.Index(
                        fields=["subscription_status"],
                        name="etop_backen_subscri_f31904_idx",
                    ),
                    models.Index(
                        fields=["subscribed_at"], name="etop_backen_subscri_fd787a_idx"
                    ),
                    models.Index(
                        fields=["sales_associate"],
                        name="etop_backen_sales_a_b0b9eb_idx",
                    ),
                ],
            },
        ),
    ]
