# Generated by Django 4.2.27 on 2025-12-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0003_emailsubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dealership_name",
                    models.CharField(
                        help_text="The official name of your dealership",
                        max_length=200,
                        verbose_name="Dealership Name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Your dealership's tagline or slogan",
                        max_length=200,
                        verbose_name="Tagline/Slogan",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your dealership logo",
                        null=True,
                        upload_to="dealership/logos/",
                        verbose_name="Dealership Logo",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Complete physical address",
                        verbose_name="Full Address",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal/ZIP Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Ethiopia", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude coordinate (e.g., 9.019150)",
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude coordinate (e.g., 38.752869)",
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "map_zoom_level",
                    models.IntegerField(
                        default=15,
                        help_text="Default zoom level for maps (1-20)",
                        verbose_name="Map Zoom Level",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Main contact phone number",
                        max_length=20,
                        verbose_name="Primary Phone",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Additional phone number",
                        max_length=20,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer support email",
                        max_length=254,
                        verbose_name="Support Email",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official website address",
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "monday_open",
                    models.TimeField(default="08:00", verbose_name="Monday Open"),
                ),
                (
                    "monday_close",
                    models.TimeField(default="18:00", verbose_name="Monday Close"),
                ),
                (
                    "tuesday_open",
                    models.TimeField(default="08:00", verbose_name="Tuesday Open"),
                ),
                (
                    "tuesday_close",
                    models.TimeField(default="18:00", verbose_name="Tuesday Close"),
                ),
                (
                    "wednesday_open",
                    models.TimeField(default="08:00", verbose_name="Wednesday Open"),
                ),
                (
                    "wednesday_close",
                    models.TimeField(default="18:00", verbose_name="Wednesday Close"),
                ),
                (
                    "thursday_open",
                    models.TimeField(default="08:00", verbose_name="Thursday Open"),
                ),
                (
                    "thursday_close",
                    models.TimeField(default="18:00", verbose_name="Thursday Close"),
                ),
                (
                    "friday_open",
                    models.TimeField(default="08:00", verbose_name="Friday Open"),
                ),
                (
                    "friday_close",
                    models.TimeField(default="18:00", verbose_name="Friday Close"),
                ),
                (
                    "saturday_open",
                    models.TimeField(default="09:00", verbose_name="Saturday Open"),
                ),
                (
                    "saturday_close",
                    models.TimeField(default="17:00", verbose_name="Saturday Close"),
                ),
                (
                    "sunday_open",
                    models.TimeField(
                        blank=True,
                        default="10:00",
                        null=True,
                        verbose_name="Sunday Open",
                    ),
                ),
                (
                    "sunday_close",
                    models.TimeField(
                        blank=True,
                        default="16:00",
                        null=True,
                        verbose_name="Sunday Close",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter/X URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="YouTube URL"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of your dealership",
                        verbose_name="Description",
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(
                        blank=True,
                        help_text="Your dealership's mission statement",
                        verbose_name="Mission Statement",
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        blank=True,
                        help_text="Your dealership's vision statement",
                        verbose_name="Vision Statement",
                    ),
                ),
                (
                    "core_values",
                    models.TextField(
                        blank=True,
                        help_text="List your core values",
                        verbose_name="Core Values",
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="Brief history of your dealership",
                        verbose_name="History",
                    ),
                ),
                (
                    "services_offered",
                    models.TextField(
                        blank=True,
                        help_text="List services offered (e.g., Financing, Trade-ins, Maintenance)",
                        verbose_name="Services Offered",
                    ),
                ),
                (
                    "brands_carried",
                    models.TextField(
                        blank=True,
                        help_text="List of car brands you carry",
                        verbose_name="Brands Carried",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to active to display on website",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us",},
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("sales", "Sales Associate"),
                            ("mechanic", "Mechanic"),
                            ("finance", "Finance Manager"),
                            ("customer_service", "Customer Service"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                (
                    "custom_position",
                    models.CharField(
                        blank=True,
                        help_text="If 'Other' is selected, specify position here",
                        max_length=100,
                        verbose_name="Custom Position",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="Years of Experience"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which team members are displayed",
                        verbose_name="Display Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "about_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="etop_backend.aboutus",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["display_order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="DealershipPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="dealership/photos/", verbose_name="Photo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("showroom", "Showroom"),
                            ("facility", "Facility"),
                            ("workshop", "Workshop"),
                            ("exterior", "Exterior"),
                            ("team", "Team"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        default="showroom",
                        max_length=20,
                        verbose_name="Photo Type",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "about_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="etop_backend.aboutus",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealership Photo",
                "verbose_name_plural": "Dealership Photos",
                "ordering": ["display_order", "-uploaded_at"],
            },
        ),
    ]
