# Generated by Django 4.2.27 on 2025-12-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0004_aboutus_teammember_dealershipphoto"),
    ]

    operations = [
        migrations.RemoveField(model_name="dealershipphoto", name="about_us",),
        migrations.RemoveField(model_name="teammember", name="about_us",),
        migrations.DeleteModel(name="AboutUs",),
        migrations.DeleteModel(name="DealershipPhoto",),
        migrations.DeleteModel(name="TeamMember",),
    ]
