# Generated by Django 4.2.27 on 2025-12-18 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import etop_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_service_servicecategory_servicetestimonial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etop_backend", "0005_remove_dealershipphoto_about_us_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_make", models.CharField(blank=True, max_length=100)),
                ("custom_model", models.CharField(blank=True, max_length=100)),
                (
                    "custom_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                ("license_plate", models.CharField(max_length=20)),
                (
                    "vin",
                    models.CharField(
                        max_length=17, verbose_name="Vehicle Identification Number"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("our_dealership", "Purchased from Our Dealership"),
                            ("other_dealership", "Purchased from Other Dealership"),
                            ("private_sale", "Private Sale"),
                            ("company_fleet", "Company Fleet"),
                            ("rental", "Rental Vehicle"),
                            ("other", "Other"),
                        ],
                        default="our_dealership",
                        max_length=20,
                    ),
                ),
                ("purchased_from_us", models.BooleanField(default=False)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_odometer",
                    models.IntegerField(
                        blank=True,
                        help_text="Odometer reading at purchase (km)",
                        null=True,
                    ),
                ),
                ("sales_invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "current_odometer",
                    models.IntegerField(
                        help_text="Current odometer reading in kilometers"
                    ),
                ),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("last_service_odometer", models.IntegerField(blank=True, null=True)),
                ("last_service_type", models.CharField(blank=True, max_length=100)),
                ("has_warranty", models.BooleanField(default=False)),
                ("warranty_start_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("warranty_type", models.CharField(blank=True, max_length=100)),
                ("warranty_terms", models.TextField(blank=True)),
                ("is_neta_car", models.BooleanField(default=False)),
                (
                    "neta_battery_warranty_years",
                    models.IntegerField(
                        default=2, help_text="NETA battery warranty years"
                    ),
                ),
                (
                    "neta_battery_warranty_km",
                    models.IntegerField(
                        default=50000, help_text="NETA battery warranty kilometers"
                    ),
                ),
                ("is_eligible_for_10000km_service", models.BooleanField(default=False)),
                (
                    "next_service_due_km",
                    models.IntegerField(
                        blank=True,
                        help_text="Next service due at this kilometer reading",
                        null=True,
                    ),
                ),
                (
                    "next_service_due_date",
                    models.DateField(
                        blank=True, help_text="Next service due date", null=True
                    ),
                ),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "electric_car",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is one of our electric car models",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_vehicles",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Vehicle",
                "verbose_name_plural": "Customer Vehicles",
                "ordering": ["-created_at"],
                "unique_together": {("license_plate", "vin")},
            },
        ),
        migrations.CreateModel(
            name="ServiceReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming_service", "Upcoming Service"),
                            ("warranty_expiry", "Warranty Expiry"),
                            ("regular_maintenance", "Regular Maintenance"),
                            ("recall_notice", "Recall Notice"),
                            ("promotional", "Promotional Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reminder_date", models.DateField()),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_send_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="etop_backend.customervehicle",
                    ),
                ),
            ],
            options={"ordering": ["scheduled_send_date"],},
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        default=etop_backend.models.generate_booking_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("neta_warranty", "NETA 2-Year Warranty Service"),
                            ("10000km_service", "10,000 KM Service"),
                            ("routine_maintenance", "Routine Maintenance"),
                            ("battery_service", "Battery Service"),
                            ("diagnostic", "Diagnostic Check"),
                            ("repair", "Repair Service"),
                            ("recall_service", "Recall Service"),
                            ("pre_purchase_inspection", "Pre-Purchase Inspection"),
                            ("other", "Other"),
                        ],
                        default="routine_maintenance",
                        max_length=50,
                    ),
                ),
                (
                    "service_type_custom",
                    models.CharField(
                        blank=True,
                        help_text="Custom service type if 'other' is selected",
                        max_length=100,
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time_slot", models.TimeField()),
                (
                    "alternative_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of alternative dates in YYYY-MM-DD format",
                    ),
                ),
                (
                    "odometer_reading",
                    models.IntegerField(
                        help_text="Current odometer reading at time of booking"
                    ),
                ),
                (
                    "service_description",
                    models.TextField(
                        blank=True, help_text="Detailed description of service needed"
                    ),
                ),
                (
                    "symptoms_problems",
                    models.TextField(
                        blank=True, help_text="Describe any symptoms or problems"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                            ("warranty", "Warranty Claim"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_odometer", models.IntegerField(blank=True, null=True)),
                ("service_report", models.TextField(blank=True)),
                (
                    "parts_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of parts used with IDs and quantities",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("warranty_covered", models.BooleanField(default=False)),
                ("warranty_claim_number", models.CharField(blank=True, max_length=50)),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("follow_up_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Technicians"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to specific service from company app",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="company.service",
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="company.servicecenter",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_bookings",
                        to="etop_backend.customervehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Booking",
                "verbose_name_plural": "Service Bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking_number"], name="etop_backen_booking_e88e01_idx"
                    ),
                    models.Index(
                        fields=["status"], name="etop_backen_status_e3a025_idx"
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="etop_backen_schedul_d23582_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="etop_backen_custome_557ef6_idx"
                    ),
                ],
            },
        ),
    ]
