# Generated by Django 4.2.27 on 2025-12-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0006_customervehicle_servicereminder_servicebooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebooking",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_bookings",
                to="etop_backend.electriccar",
            ),
        ),
    ]
