# Generated by Django 4.2.27 on 2025-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0007_alter_servicebooking_vehicle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servicebooking",
            new_name="etop_backen_custome_899d05_idx",
            old_name="etop_backen_custome_557ef6_idx",
        ),
        migrations.AlterField(
            model_name="servicebooking",
            name="customer",
            field=models.CharField(
                help_text="Full name of the customer", max_length=255
            ),
        ),
    ]
