# Generated by Django 4.2.27 on 2025-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "etop_backend",
            "0008_rename_etop_backen_custome_557ef6_idx_etop_backen_custome_899d05_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicebooking",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("neta_warranty", "NETA 2-Year Warranty Service"),
                    ("10000km_service", "10,000 KM Service"),
                ],
                default="routine_maintenance",
                max_length=50,
            ),
        ),
    ]
