# Generated by Django 4.2.27 on 2025-12-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0009_alter_servicebooking_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField(help_text="Message sent by the customer")),
                (
                    "preferred_contact_time",
                    models.CharField(
                        choices=[
                            ("6h", "Within 6 hours"),
                            ("24h", "Within 24 hours"),
                            ("48h", "Within 48 hours"),
                        ],
                        default="24h",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "electric_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_orders",
                        to="etop_backend.electriccar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Order",
                "verbose_name_plural": "Contact Orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
