# Generated by Django 4.2.27 on 2025-12-19 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etop_backend", "0010_contactorder"),
    ]

    operations = [
        migrations.AlterModelOptions(name="electriccar", options={},),
        migrations.AlterUniqueTogether(name="electriccar", unique_together=set(),),
        migrations.AlterField(
            model_name="electriccar",
            name="autopilot_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="available_exterior_colors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"color_type": "exterior"},
                related_name="available_exterior_cars",
                to="etop_backend.carcolor",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="available_interior_colors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"color_type": "interior"},
                related_name="available_interior_cars",
                to="etop_backend.carcolor",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="base_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total battery capacity in kWh",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lithium_ion", "Lithium-Ion"),
                    ("lithium_polymer", "Lithium Polymer"),
                    ("solid_state", "Solid State"),
                    ("lifepo4", "Lithium Iron Phosphate (LiFePO4)"),
                    ("nmc", "NMC (Nickel Manganese Cobalt)"),
                    ("lto", "LTO (Lithium Titanate)"),
                ],
                default="lithium_ion",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_km",
            field=models.IntegerField(
                blank=True,
                default=160000,
                help_text="Warranty in kilometers",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_years",
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="cargo_capacity",
            field=models.IntegerField(
                blank=True, help_text="Cargo capacity in liters", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("crossover", "Crossover"),
                    ("hatchback", "Hatchback"),
                    ("coupe", "Coupe"),
                    ("convertible", "Convertible"),
                    ("sports", "Sports Car"),
                    ("pickup", "Pickup Truck"),
                    ("van", "Van/Minibus"),
                    ("luxury", "Luxury"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_port_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_time_10_80",
            field=models.IntegerField(
                blank=True,
                help_text="Time to charge from 10% to 80% at max DC power (minutes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("type1", "Type 1 (SAE J1772)"),
                    ("type2", "Type 2 (Mennekes)"),
                    ("ccs1", "CCS1 (Combo 1)"),
                    ("ccs2", "CCS2 (Combo 2)"),
                    ("chademo", "CHAdeMO"),
                    ("tesla", "Tesla Supercharger"),
                    ("gb_t", "GB/T (China)"),
                    ("nacs", "NACS (Tesla Standard)"),
                ],
                default="ccs2",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="curb_weight",
            field=models.IntegerField(
                blank=True, help_text="Curb weight in kg", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="estimated_delivery",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="has_v2g",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="has_v2l",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="height",
            field=models.IntegerField(blank=True, help_text="Height in mm", null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="key_features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="length",
            field=models.IntegerField(blank=True, help_text="Length in mm", null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_ac_charging",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum AC charging power in kW",
                null=True,
                verbose_name="Max AC Charging",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_dc_charging",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum DC charging power in kW",
                null=True,
                verbose_name="Max DC Charging",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="model_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2008),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="range_wltp",
            field=models.IntegerField(
                blank=True,
                help_text="WLTP range in km",
                null=True,
                verbose_name="WLTP Range",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="regen_braking_levels",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="safety_features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="seating_capacity",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available for Sale"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("test_drive", "Available for Test Drive"),
                    ("coming_soon", "Coming Soon"),
                    ("pre_order", "Pre-order Available"),
                    ("display", "Display Model Only"),
                ],
                default="available",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="tax_incentive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="variant",
            field=models.CharField(
                blank=True,
                help_text="e.g., Long Range, Performance, Standard",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="width",
            field=models.IntegerField(blank=True, help_text="Width in mm", null=True),
        ),
    ]
