# Generated by Django 4.2.27 on 2025-12-19 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etop_backend", "0011_alter_electriccar_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electriccar",
            options={
                "ordering": ["manufacturer", "model_name", "model_year"],
                "verbose_name": "Electric Car",
                "verbose_name_plural": "Electric Cars",
            },
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="autopilot_level",
            field=models.CharField(
                choices=[
                    ("none", "No Autopilot"),
                    ("basic", "Basic Driver Assistance"),
                    ("level2", "Level 2 Autonomy"),
                    ("level3", "Level 3 Autonomy"),
                    ("level4", "Level 4 Autonomy"),
                ],
                default="basic",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="available_exterior_colors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available exterior color options",
                limit_choices_to={"color_type": "exterior"},
                related_name="available_exterior_cars",
                to="etop_backend.carcolor",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="available_interior_colors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Available interior color options",
                limit_choices_to={"color_type": "interior"},
                related_name="available_interior_cars",
                to="etop_backend.carcolor",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Base price in ETB", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_capacity",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Total battery capacity in kWh",
                max_digits=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_type",
            field=models.CharField(
                choices=[
                    ("lithium_ion", "Lithium-Ion"),
                    ("lithium_polymer", "Lithium Polymer"),
                    ("solid_state", "Solid State"),
                    ("lifepo4", "Lithium Iron Phosphate (LiFePO4)"),
                    ("nmc", "NMC (Nickel Manganese Cobalt)"),
                    ("lto", "LTO (Lithium Titanate)"),
                ],
                default="lithium_ion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_km",
            field=models.IntegerField(
                default=160000, help_text="Warranty in kilometers"
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_years",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="cargo_capacity",
            field=models.IntegerField(
                default=450, help_text="Cargo capacity in liters"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="category",
            field=models.CharField(
                choices=[
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("crossover", "Crossover"),
                    ("hatchback", "Hatchback"),
                    ("coupe", "Coupe"),
                    ("convertible", "Convertible"),
                    ("sports", "Sports Car"),
                    ("pickup", "Pickup Truck"),
                    ("van", "Van/Minibus"),
                    ("luxury", "Luxury"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_port_location",
            field=models.CharField(
                choices=[
                    ("front_left", "Front Left"),
                    ("front_right", "Front Right"),
                    ("rear_left", "Rear Left"),
                    ("rear_right", "Rear Right"),
                    ("front", "Front Center"),
                    ("rear", "Rear Center"),
                ],
                default="rear_left",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_time_10_80",
            field=models.IntegerField(
                default=35,
                help_text="Time to charge from 10% to 80% at max DC power (minutes)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_type",
            field=models.CharField(
                choices=[
                    ("type1", "Type 1 (SAE J1772)"),
                    ("type2", "Type 2 (Mennekes)"),
                    ("ccs1", "CCS1 (Combo 1)"),
                    ("ccs2", "CCS2 (Combo 2)"),
                    ("chademo", "CHAdeMO"),
                    ("tesla", "Tesla Supercharger"),
                    ("gb_t", "GB/T (China)"),
                    ("nacs", "NACS (Tesla Standard)"),
                ],
                default="ccs2",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="curb_weight",
            field=models.IntegerField(default=1750, help_text="Curb weight in kg"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="description",
            field=models.TextField(default="New performant electric car"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="estimated_delivery",
            field=models.CharField(
                blank=True,
                default="4-8 weeks",
                help_text="Estimated delivery time",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="has_v2g",
            field=models.BooleanField(
                default=False,
                help_text="Can supply power back to grid",
                verbose_name="Vehicle-to-Grid",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="has_v2l",
            field=models.BooleanField(
                default=False,
                help_text="Can power external devices",
                verbose_name="Vehicle-to-Load",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="height",
            field=models.IntegerField(default=1500, help_text="Height in mm"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="key_features",
            field=models.TextField(help_text="List key features separated by commas"),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="length",
            field=models.IntegerField(default=4500, help_text="Length in mm"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_ac_charging",
            field=models.IntegerField(
                default=11,
                help_text="Maximum AC charging power in kW",
                verbose_name="Max AC Charging",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_dc_charging",
            field=models.IntegerField(
                default=100,
                help_text="Maximum DC charging power in kW",
                verbose_name="Max DC Charging",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="model_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2008),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="range_wltp",
            field=models.IntegerField(
                help_text="WLTP range in km", verbose_name="WLTP Range"
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="regen_braking_levels",
            field=models.IntegerField(
                default=1, help_text="Number of regenerative braking levels"
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="safety_features",
            field=models.TextField(blank=True, help_text="Safety features"),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="seating_capacity",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available for Sale"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("test_drive", "Available for Test Drive"),
                    ("coming_soon", "Coming Soon"),
                    ("pre_order", "Pre-order Available"),
                    ("display", "Display Model Only"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="tax_incentive",
            field=models.BooleanField(
                default=False, help_text="Eligible for government tax incentives"
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="variant",
            field=models.CharField(
                blank=True,
                help_text="e.g., Long Range, Performance, Standard",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="width",
            field=models.IntegerField(help_text="Width in mm"),
        ),
        migrations.AlterUniqueTogether(
            name="electriccar",
            unique_together={("manufacturer", "model_name", "variant", "model_year")},
        ),
    ]
