# Generated by Django 4.2.27 on 2025-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0012_alter_electriccar_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electriccar",
            name="acceleration_0_100",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="0-100 km/h acceleration in seconds",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total battery capacity in kWh",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_km",
            field=models.IntegerField(
                blank=True,
                default=160000,
                help_text="Warranty in kilometers",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="battery_warranty_years",
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="cargo_capacity",
            field=models.IntegerField(
                blank=True, help_text="Cargo capacity in liters", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_time_10_80",
            field=models.IntegerField(
                blank=True,
                help_text="Time to charge from 10% to 80% at max DC power (minutes)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="charging_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("type1", "Type 1 (SAE J1772)"),
                    ("type2", "Type 2 (Mennekes)"),
                    ("ccs1", "CCS1 (Combo 1)"),
                    ("ccs2", "CCS2 (Combo 2)"),
                    ("chademo", "CHAdeMO"),
                    ("tesla", "Tesla Supercharger"),
                    ("gb_t", "GB/T (China)"),
                    ("nacs", "NACS (Tesla Standard)"),
                ],
                default="ccs2",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="curb_weight",
            field=models.IntegerField(
                blank=True, help_text="Curb weight in kg", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="drive_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rwd", "Rear Wheel Drive"),
                    ("fwd", "Front Wheel Drive"),
                    ("awd", "All Wheel Drive"),
                    ("dual_motor", "Dual Motor AWD"),
                    ("tri_motor", "Tri Motor AWD"),
                    ("quad_motor", "Quad Motor AWD"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="featured",
            field=models.BooleanField(
                blank=True, default=False, help_text="Featured on homepage", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="height",
            field=models.IntegerField(blank=True, help_text="Height in mm", null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="key_features",
            field=models.TextField(
                blank=True, help_text="List key features separated by commas", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="length",
            field=models.IntegerField(blank=True, help_text="Length in mm", null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_ac_charging",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum AC charging power in kW",
                null=True,
                verbose_name="Max AC Charging",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="max_dc_charging",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum DC charging power in kW",
                null=True,
                verbose_name="Max DC Charging",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="motor_power",
            field=models.IntegerField(
                blank=True, help_text="Total motor power in kW", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="range_wltp",
            field=models.IntegerField(
                blank=True,
                help_text="WLTP range in km",
                null=True,
                verbose_name="WLTP Range",
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="seating_capacity",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available for Sale"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("test_drive", "Available for Test Drive"),
                    ("coming_soon", "Coming Soon"),
                    ("pre_order", "Pre-order Available"),
                    ("display", "Display Model Only"),
                ],
                default="available",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="top_speed",
            field=models.IntegerField(
                blank=True, help_text="Top speed in km/h", null=True
            ),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="torque",
            field=models.IntegerField(blank=True, help_text="Torque in Nm", null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="electriccar",
            name="width",
            field=models.IntegerField(blank=True, help_text="Width in mm", null=True),
        ),
    ]
