# Generated by Django 4.2.27 on 2025-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0013_alter_electriccar_acceleration_0_100_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactorder",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
