# Generated by Django 4.2.27 on 2025-12-20 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_service_servicecategory_servicetestimonial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("etop_backend", "0014_contactorder_is_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bookings",
                    models.ManyToManyField(
                        related_name="schedules", to="etop_backend.servicebooking"
                    ),
                ),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company.servicecenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Service",
                "verbose_name_plural": "Scheduled Services",
            },
        ),
    ]
