# Generated by Django 4.2.27 on 2025-12-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0015_scheduleservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="customer_email",
            field=models.EmailField(
                default="", help_text="Email address of the customer", max_length=255
            ),
            preserve_default=False,
        ),
    ]
