# Generated by Django 4.2.27 on 2025-12-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0016_servicebooking_customer_email"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="servicebooking", name="etop_backen_schedul_d23582_idx",
        ),
        migrations.RemoveField(model_name="servicebooking", name="scheduled_at",),
        migrations.RemoveField(model_name="servicebooking", name="scheduled_by",),
        migrations.RemoveField(model_name="servicebooking", name="scheduled_date",),
        migrations.RemoveField(model_name="servicebooking", name="scheduled_time",),
        migrations.AddField(
            model_name="servicebooking",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the customer",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicebooking",
            name="is_scheduled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this service has been scheduled via ScheduleService",
            ),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["is_scheduled"], name="etop_backen_is_sche_1b38d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicebooking",
            index=models.Index(
                fields=["preferred_date"], name="etop_backen_preferr_6027b4_idx"
            ),
        ),
    ]
