# Generated by Django 4.2.27 on 2025-12-20 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "etop_backend",
            "0017_remove_servicebooking_etop_backen_schedul_d23582_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
