# Generated by Django 4.2.27 on 2025-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0018_manufacturer_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
