# Generated by Django 4.2.27 on 2025-12-23 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dealership_name",
                    models.CharField(
                        help_text="The official name of your dealership",
                        max_length=200,
                        verbose_name="Dealership Name",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Your dealership's tagline or slogan",
                        max_length=200,
                        verbose_name="Tagline/Slogan",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload your dealership logo",
                        null=True,
                        upload_to="dealership/logos/",
                        verbose_name="Dealership Logo",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Complete physical address",
                        verbose_name="Full Address",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state_province",
                    models.CharField(max_length=100, verbose_name="State/Province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal/ZIP Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Ethiopia", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude coordinate (e.g., 9.019150)",
                        max_digits=9,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude coordinate (e.g., 38.752869)",
                        max_digits=9,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "map_zoom_level",
                    models.IntegerField(
                        default=15,
                        help_text="Default zoom level for maps (1-20)",
                        verbose_name="Map Zoom Level",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Main contact phone number",
                        max_length=20,
                        verbose_name="Primary Phone",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        help_text="Additional phone number",
                        max_length=20,
                        verbose_name="Secondary Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer support email",
                        max_length=254,
                        verbose_name="Support Email",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official website address",
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "monday_open",
                    models.TimeField(default="08:00", verbose_name="Monday Open"),
                ),
                (
                    "monday_close",
                    models.TimeField(default="18:00", verbose_name="Monday Close"),
                ),
                (
                    "tuesday_open",
                    models.TimeField(default="08:00", verbose_name="Tuesday Open"),
                ),
                (
                    "tuesday_close",
                    models.TimeField(default="18:00", verbose_name="Tuesday Close"),
                ),
                (
                    "wednesday_open",
                    models.TimeField(default="08:00", verbose_name="Wednesday Open"),
                ),
                (
                    "wednesday_close",
                    models.TimeField(default="18:00", verbose_name="Wednesday Close"),
                ),
                (
                    "thursday_open",
                    models.TimeField(default="08:00", verbose_name="Thursday Open"),
                ),
                (
                    "thursday_close",
                    models.TimeField(default="18:00", verbose_name="Thursday Close"),
                ),
                (
                    "friday_open",
                    models.TimeField(default="08:00", verbose_name="Friday Open"),
                ),
                (
                    "friday_close",
                    models.TimeField(default="18:00", verbose_name="Friday Close"),
                ),
                (
                    "saturday_open",
                    models.TimeField(default="09:00", verbose_name="Saturday Open"),
                ),
                (
                    "saturday_close",
                    models.TimeField(default="17:00", verbose_name="Saturday Close"),
                ),
                (
                    "sunday_open",
                    models.TimeField(
                        blank=True,
                        default="10:00",
                        null=True,
                        verbose_name="Sunday Open",
                    ),
                ),
                (
                    "sunday_close",
                    models.TimeField(
                        blank=True,
                        default="16:00",
                        null=True,
                        verbose_name="Sunday Close",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, verbose_name="Facebook URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter/X URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="YouTube URL"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of your dealership",
                        verbose_name="Description",
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(
                        blank=True,
                        help_text="Your dealership's mission statement",
                        verbose_name="Mission Statement",
                    ),
                ),
                (
                    "vision_statement",
                    models.TextField(
                        blank=True,
                        help_text="Your dealership's vision statement",
                        verbose_name="Vision Statement",
                    ),
                ),
                (
                    "core_values",
                    models.TextField(
                        blank=True,
                        help_text="List your core values",
                        verbose_name="Core Values",
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="Brief history of your dealership",
                        verbose_name="History",
                    ),
                ),
                (
                    "services_offered",
                    models.TextField(
                        blank=True,
                        help_text="List services offered (e.g., Financing, Trade-ins, Maintenance)",
                        verbose_name="Services Offered",
                    ),
                ),
                (
                    "brands_carried",
                    models.TextField(
                        blank=True,
                        help_text="List of car brands you carry",
                        verbose_name="Brands Carried",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to active to display on website",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us",},
        ),
        migrations.CreateModel(
            name="DealershipPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="dealership/photos/", verbose_name="Photo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("showroom", "Showroom"),
                            ("facility", "Facility"),
                            ("workshop", "Workshop"),
                            ("exterior", "Exterior"),
                            ("team", "Team"),
                            ("event", "Event"),
                            ("other", "Other"),
                        ],
                        default="showroom",
                        max_length=20,
                        verbose_name="Photo Type",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dealership Photo",
                "verbose_name_plural": "Dealership Photos",
                "ordering": ["display_order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description for event listing", max_length=500
                    ),
                ),
                ("detailed_description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                            ("workshop", "Workshop"),
                            ("meetup", "Meetup"),
                            ("trade_show", "Trade Show"),
                            ("product_launch", "Product Launch"),
                            ("press_event", "Press Event"),
                            ("networking", "Networking Event"),
                            ("training", "Training Session"),
                            ("virtual", "Virtual Event"),
                            ("hybrid", "Hybrid Event"),
                            ("other", "Other"),
                        ],
                        default="conference",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Event timezone (e.g., 'America/New_York', 'UTC')",
                        max_length=100,
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("virtual_platform", models.CharField(blank=True, max_length=100)),
                ("virtual_link", models.URLField(blank=True)),
                ("virtual_meeting_id", models.CharField(blank=True, max_length=100)),
                ("virtual_passcode", models.CharField(blank=True, max_length=100)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cover image for the event",
                        null=True,
                        upload_to="events/covers/",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="Banner image for event details page",
                        null=True,
                        upload_to="events/banners/",
                    ),
                ),
                ("requires_registration", models.BooleanField(default=True)),
                ("is_free", models.BooleanField(default=True)),
                ("registration_link", models.URLField(blank=True)),
                (
                    "max_attendees",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("current_attendees", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Price per attendee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="ETB", max_length=3, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True, max_length=300)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., 'fa-calendar')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for category",
                        max_length=7,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Event Category",
                "verbose_name_plural": "Event Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["display_order", "uploaded_at"],},
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("dietary_preferences", models.CharField(blank=True, max_length=200)),
                ("special_requirements", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=True)),
                ("checked_in", models.BooleanField(default=False)),
                ("checkin_time", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=200)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={"ordering": ["-registration_date"],},
        ),
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Event Schedule",
                "verbose_name_plural": "Event Schedules",
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/speakers/"
                    ),
                ),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["display_order", "name"],},
        ),
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="EventWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["joined_at"],},
        ),
        migrations.CreateModel(
            name="FinanceCalculator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "calculator_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan Calculator"),
                            ("lease", "Lease Calculator"),
                            ("affordability", "Affordability Calculator"),
                            ("comparison", "Loan Comparison"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "example_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=30000.0, max_digits=10
                    ),
                ),
                (
                    "example_interest_rate",
                    models.DecimalField(decimal_places=2, default=5.99, max_digits=4),
                ),
                ("example_term_months", models.IntegerField(default=60)),
                (
                    "example_down_payment",
                    models.DecimalField(
                        decimal_places=2, default=3000.0, max_digits=10
                    ),
                ),
                (
                    "example_monthly_payment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "example_total_interest",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "example_total_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("required", "Required Document"),
                            ("helpful", "Helpful Document"),
                            ("form", "Application Form"),
                            ("guide", "Guide/FAQ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("file", models.FileField(blank=True, upload_to="finance/documents/")),
                ("external_url", models.URLField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-file",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["document_type", "display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceFAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("eligibility", "Eligibility"),
                            ("process", "Application Process"),
                            ("rates", "Rates & Terms"),
                            ("documents", "Required Documents"),
                            ("payment", "Payments"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Finance FAQ",
                "verbose_name_plural": "Finance FAQs",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="FinanceFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class or image filename",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceInformationPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("hero_title", models.CharField(max_length=200)),
                ("hero_description", models.TextField()),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="finance/hero/"),
                ),
                (
                    "features_title",
                    models.CharField(default="Why Finance With Us?", max_length=200),
                ),
                ("features_intro", models.TextField(blank=True)),
                ("show_loan_calculator", models.BooleanField(default=True)),
                ("show_lease_calculator", models.BooleanField(default=True)),
                ("show_affordability_calculator", models.BooleanField(default=True)),
                (
                    "faq_section_title",
                    models.CharField(
                        default="Frequently Asked Questions", max_length=200
                    ),
                ),
                (
                    "offers_section_title",
                    models.CharField(default="Current Finance Offers", max_length=200),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("calculator", "Calculator Focus"),
                            ("offers", "Offers Focus"),
                            ("educational", "Educational Focus"),
                            ("comparison", "Comparison Focus"),
                        ],
                        default="calculator",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Finance Information Page",
                "verbose_name_plural": "Finance Information Pages",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FinanceOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_description", models.CharField(max_length=100)),
                ("full_description", models.TextField()),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("low_apr", "Low APR Offer"),
                            ("cashback", "Cashback Offer"),
                            ("zero_down", "Zero Down Payment"),
                            ("special_lease", "Special Lease Rate"),
                            ("loyalty", "Loyalty Bonus"),
                            ("seasonal", "Seasonal Offer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(default="Special Offer", max_length=20),
                ),
                (
                    "apr_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Percentage Rate",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cashback amount if applicable",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "down_payment_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum down payment percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "term_months",
                    models.IntegerField(
                        blank=True, help_text="Loan term in months", null=True
                    ),
                ),
                ("eligibility_requirements", models.TextField(blank=True)),
                (
                    "min_credit_score",
                    models.IntegerField(blank=True, default=600, null=True),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="finance/offers/"),
                ),
                (
                    "display_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for offer card",
                        max_length=7,
                    ),
                ),
                (
                    "display_priority",
                    models.IntegerField(default=1, help_text="1 = highest priority"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_priority", "-valid_from"],},
        ),
        migrations.CreateModel(
            name="FinancePartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="finance/partners/")),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "min_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "max_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("special_features", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Short description for news listing"),
                ),
                ("content", models.TextField(help_text="Full news content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="News image/thumbnail",
                        null=True,
                        upload_to="news/images/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=200)),
                ("full_description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("warranty", "Warranty Service"),
                            ("maintenance", "Maintenance Service"),
                            ("repair", "Repair Service"),
                            ("inspection", "Vehicle Inspection"),
                            ("installation", "Accessory Installation"),
                            ("emergency", "Emergency Service"),
                            ("consultation", "Consultation Service"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in ETB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_display",
                    models.CharField(
                        default="Contact for pricing",
                        help_text="How price appears (e.g., 'Free', 'From 5,000 ETB')",
                        max_length=100,
                    ),
                ),
                (
                    "duration_value",
                    models.IntegerField(
                        default=1, help_text="Duration number (e.g., 2 for 2 years)"
                    ),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("months", "Months"),
                            ("years", "Years"),
                            ("days", "Days"),
                            ("hours", "Hours"),
                            ("lifetime", "Lifetime"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="months",
                        max_length=10,
                    ),
                ),
                ("is_special_offer", models.BooleanField(default=False)),
                ("special_offer_text", models.CharField(blank=True, max_length=100)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("eligibility_description", models.TextField(blank=True)),
                (
                    "min_vehicle_year",
                    models.IntegerField(
                        blank=True, help_text="Minimum vehicle year eligible", null=True
                    ),
                ),
                (
                    "max_vehicle_year",
                    models.IntegerField(
                        blank=True, help_text="Maximum vehicle year eligible", null=True
                    ),
                ),
                (
                    "is_neta_battery_warranty",
                    models.BooleanField(
                        default=False,
                        help_text="Special 2-year battery warranty for NETA cars only",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features as JSON array",
                    ),
                ),
                ("service_center_required", models.BooleanField(default=True)),
                ("mobile_service_available", models.BooleanField(default=False)),
                ("appointment_required", models.BooleanField(default=True)),
                (
                    "estimated_service_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2-3 hours', '1 day'",
                        max_length=100,
                    ),
                ),
                (
                    "is_first_round_service",
                    models.BooleanField(
                        default=False, help_text="First round service for all cars"
                    ),
                ),
                ("warranty_coverage", models.TextField(blank=True)),
                ("warranty_exclusions", models.TextField(blank=True)),
                ("warranty_claim_process", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="services/featured/"),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True, null=True, upload_to="services/brochures/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class (e.g., fas fa-shield-alt)",
                        max_length=50,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for icon background",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("sales", "Sales Associate"),
                            ("mechanic", "Mechanic"),
                            ("finance", "Finance Manager"),
                            ("customer_service", "Customer Service"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Position",
                    ),
                ),
                (
                    "custom_position",
                    models.CharField(
                        blank=True,
                        help_text="If 'Other' is selected, specify position here",
                        max_length=100,
                        verbose_name="Custom Position",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="Years of Experience"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which team members are displayed",
                        verbose_name="Display Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "about_us",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="company.aboutus",
                        verbose_name="Dealership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["display_order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceTestimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "customer_vehicle",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Tesla Model 3', 'NETA V'",
                        max_length=100,
                    ),
                ),
                ("testimonial", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                    ),
                ),
                ("customer_location", models.CharField(blank=True, max_length=100)),
                ("service_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="services/testimonials/"),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="company.service",
                    ),
                ),
            ],
            options={"ordering": ["-service_date", "display_order"],},
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted package price",
                        max_digits=10,
                    ),
                ),
                (
                    "individual_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price if services purchased individually",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_percentage",
                    models.IntegerField(
                        help_text="Percentage savings",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount saved in ETB", max_digits=10
                    ),
                ),
                (
                    "recommended_for",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'New EV Owners', 'High Mileage Vehicles'",
                        max_length=200,
                    ),
                ),
                ("badge_text", models.CharField(default="Best Value", max_length=50)),
                ("display_color", models.CharField(default="#10B981", max_length=7)),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(
                        help_text="Services included in this package",
                        related_name="packages",
                        to="company.service",
                    ),
                ),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("warranty", "Warranty"),
                            ("maintenance", "Maintenance"),
                            ("pricing", "Pricing"),
                            ("process", "Service Process"),
                            ("eligibility", "Eligibility"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="company.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service FAQ",
                "verbose_name_plural": "Service FAQs",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict, help_text="JSON with day:hours pairs"
                    ),
                ),
                ("has_ev_charging", models.BooleanField(default=True)),
                ("has_waiting_lounge", models.BooleanField(default=True)),
                ("has_loaner_cars", models.BooleanField(default=False)),
                ("has_mobile_service", models.BooleanField(default=False)),
                ("is_main_center", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services_offered",
                    models.ManyToManyField(
                        blank=True, related_name="service_centers", to="company.service"
                    ),
                ),
            ],
            options={"ordering": ["-is_main_center", "city", "name"],},
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="company.servicecategory",
            ),
        ),
    ]
