# Generated by Django 4.2.27 on 2025-12-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etop_backend", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="eligible_car_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific electric car models eligible for this service",
                related_name="eligible_services",
                to="etop_backend.electriccar",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="eligible_manufacturers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Manufacturers eligible for this service",
                related_name="eligible_services",
                to="etop_backend.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financefeature",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="company.financeinformationpage",
            ),
        ),
        migrations.AddField(
            model_name="eventwaitlist",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="eventspeaker",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="eventschedule",
            name="speakers",
            field=models.ManyToManyField(blank=True, to="company.eventspeaker"),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_images",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.eventcategory",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="gallery",
            field=models.ManyToManyField(
                blank=True, related_name="gallery", to="company.eventimage"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="company.eventtag"),
        ),
        migrations.AddField(
            model_name="dealershipphoto",
            name="about_us",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="company.aboutus",
                verbose_name="Dealership",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventwaitlist", unique_together={("event", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration", unique_together={("event", "email")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="company_eve_status_443eb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type"], name="company_eve_event_t_417758_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_featured"], name="company_eve_is_feat_b0988c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_virtual"], name="company_eve_is_virt_28951b_idx"
            ),
        ),
    ]
