# Generated by Django 4.2.27 on 2025-12-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_event_eventcategory_eventtag_eventspeaker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="currency",
            field=models.CharField(blank=True, default="ETB", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Price per attendee",
                max_digits=10,
                null=True,
            ),
        ),
    ]
