# Generated by Django 4.2.27 on 2025-12-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_event_organizer_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "calculator_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan Calculator"),
                            ("lease", "Lease Calculator"),
                            ("affordability", "Affordability Calculator"),
                            ("comparison", "Loan Comparison"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "example_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=30000.0, max_digits=10
                    ),
                ),
                (
                    "example_interest_rate",
                    models.DecimalField(decimal_places=2, default=5.99, max_digits=4),
                ),
                ("example_term_months", models.IntegerField(default=60)),
                (
                    "example_down_payment",
                    models.DecimalField(
                        decimal_places=2, default=3000.0, max_digits=10
                    ),
                ),
                (
                    "example_monthly_payment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "example_total_interest",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "example_total_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("required", "Required Document"),
                            ("helpful", "Helpful Document"),
                            ("form", "Application Form"),
                            ("guide", "Guide/FAQ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("file", models.FileField(blank=True, upload_to="finance/documents/")),
                ("external_url", models.URLField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-file",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["document_type", "display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("eligibility", "Eligibility"),
                            ("process", "Application Process"),
                            ("rates", "Rates & Terms"),
                            ("documents", "Required Documents"),
                            ("payment", "Payments"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Finance FAQ",
                "verbose_name_plural": "Finance FAQs",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="FinanceInformationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("hero_title", models.CharField(max_length=200)),
                ("hero_description", models.TextField()),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="finance/hero/"),
                ),
                (
                    "features_title",
                    models.CharField(default="Why Finance With Us?", max_length=200),
                ),
                ("features_intro", models.TextField(blank=True)),
                ("show_loan_calculator", models.BooleanField(default=True)),
                ("show_lease_calculator", models.BooleanField(default=True)),
                ("show_affordability_calculator", models.BooleanField(default=True)),
                (
                    "faq_section_title",
                    models.CharField(
                        default="Frequently Asked Questions", max_length=200
                    ),
                ),
                (
                    "offers_section_title",
                    models.CharField(default="Current Finance Offers", max_length=200),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("calculator", "Calculator Focus"),
                            ("offers", "Offers Focus"),
                            ("educational", "Educational Focus"),
                            ("comparison", "Comparison Focus"),
                        ],
                        default="calculator",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Finance Information Page",
                "verbose_name_plural": "Finance Information Pages",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FinanceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_description", models.CharField(max_length=100)),
                ("full_description", models.TextField()),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("low_apr", "Low APR Offer"),
                            ("cashback", "Cashback Offer"),
                            ("zero_down", "Zero Down Payment"),
                            ("special_lease", "Special Lease Rate"),
                            ("loyalty", "Loyalty Bonus"),
                            ("seasonal", "Seasonal Offer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(default="Special Offer", max_length=20),
                ),
                (
                    "apr_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Percentage Rate",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cashback amount if applicable",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "down_payment_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum down payment percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "term_months",
                    models.IntegerField(
                        blank=True, help_text="Loan term in months", null=True
                    ),
                ),
                ("eligibility_requirements", models.TextField(blank=True)),
                (
                    "min_credit_score",
                    models.IntegerField(blank=True, default=600, null=True),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="finance/offers/"),
                ),
                (
                    "display_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for offer card",
                        max_length=7,
                    ),
                ),
                (
                    "display_priority",
                    models.IntegerField(default=1, help_text="1 = highest priority"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_priority", "-valid_from"],},
        ),
        migrations.CreateModel(
            name="FinancePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="finance/partners/")),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "min_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "max_apr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("special_features", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="FinanceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class or image filename",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="company.financeinformationpage",
                    ),
                ),
            ],
            options={"ordering": ["display_order"],},
        ),
    ]
