# Generated by Django 4.2.27 on 2025-12-17 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("etop_backend", "0005_remove_dealershipphoto_about_us_and_more"),
        ("company", "0005_financecalculator_financedocument_financefaq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=200)),
                ("full_description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("warranty", "Warranty Service"),
                            ("maintenance", "Maintenance Service"),
                            ("repair", "Repair Service"),
                            ("inspection", "Vehicle Inspection"),
                            ("installation", "Accessory Installation"),
                            ("emergency", "Emergency Service"),
                            ("consultation", "Consultation Service"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in ETB",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_display",
                    models.CharField(
                        default="Contact for pricing",
                        help_text="How price appears (e.g., 'Free', 'From 5,000 ETB')",
                        max_length=100,
                    ),
                ),
                (
                    "duration_value",
                    models.IntegerField(
                        default=1, help_text="Duration number (e.g., 2 for 2 years)"
                    ),
                ),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("months", "Months"),
                            ("years", "Years"),
                            ("days", "Days"),
                            ("hours", "Hours"),
                            ("lifetime", "Lifetime"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="months",
                        max_length=10,
                    ),
                ),
                ("is_special_offer", models.BooleanField(default=False)),
                ("special_offer_text", models.CharField(blank=True, max_length=100)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("eligibility_description", models.TextField(blank=True)),
                (
                    "min_vehicle_year",
                    models.IntegerField(
                        blank=True, help_text="Minimum vehicle year eligible", null=True
                    ),
                ),
                (
                    "max_vehicle_year",
                    models.IntegerField(
                        blank=True, help_text="Maximum vehicle year eligible", null=True
                    ),
                ),
                (
                    "is_neta_battery_warranty",
                    models.BooleanField(
                        default=False,
                        help_text="Special 2-year battery warranty for NETA cars only",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features as JSON array",
                    ),
                ),
                ("service_center_required", models.BooleanField(default=True)),
                ("mobile_service_available", models.BooleanField(default=False)),
                ("appointment_required", models.BooleanField(default=True)),
                (
                    "estimated_service_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2-3 hours', '1 day'",
                        max_length=100,
                    ),
                ),
                (
                    "is_first_round_service",
                    models.BooleanField(
                        default=False, help_text="First round service for all cars"
                    ),
                ),
                ("warranty_coverage", models.TextField(blank=True)),
                ("warranty_exclusions", models.TextField(blank=True)),
                ("warranty_claim_process", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="services/featured/"),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True, null=True, upload_to="services/brochures/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome icon class (e.g., fas fa-shield-alt)",
                        max_length=50,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color for icon background",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "customer_vehicle",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Tesla Model 3', 'NETA V'",
                        max_length=100,
                    ),
                ),
                ("testimonial", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                    ),
                ),
                ("customer_location", models.CharField(blank=True, max_length=100)),
                ("service_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="services/testimonials/"),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="company.service",
                    ),
                ),
            ],
            options={"ordering": ["-service_date", "display_order"],},
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted package price",
                        max_digits=10,
                    ),
                ),
                (
                    "individual_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price if services purchased individually",
                        max_digits=10,
                    ),
                ),
                (
                    "savings_percentage",
                    models.IntegerField(
                        help_text="Percentage savings",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "savings_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount saved in ETB", max_digits=10
                    ),
                ),
                (
                    "recommended_for",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'New EV Owners', 'High Mileage Vehicles'",
                        max_length=200,
                    ),
                ),
                ("badge_text", models.CharField(default="Best Value", max_length=50)),
                ("display_color", models.CharField(default="#10B981", max_length=7)),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(
                        help_text="Services included in this package",
                        related_name="packages",
                        to="company.service",
                    ),
                ),
            ],
            options={"ordering": ["display_order"],},
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("warranty", "Warranty"),
                            ("maintenance", "Maintenance"),
                            ("pricing", "Pricing"),
                            ("process", "Service Process"),
                            ("eligibility", "Eligibility"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="company.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service FAQ",
                "verbose_name_plural": "Service FAQs",
                "ordering": ["category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict, help_text="JSON with day:hours pairs"
                    ),
                ),
                ("has_ev_charging", models.BooleanField(default=True)),
                ("has_waiting_lounge", models.BooleanField(default=True)),
                ("has_loaner_cars", models.BooleanField(default=False)),
                ("has_mobile_service", models.BooleanField(default=False)),
                ("is_main_center", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services_offered",
                    models.ManyToManyField(
                        blank=True, related_name="service_centers", to="company.service"
                    ),
                ),
            ],
            options={"ordering": ["-is_main_center", "city", "name"],},
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="company.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="eligible_car_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific electric car models eligible for this service",
                related_name="eligible_services",
                to="etop_backend.electriccar",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="eligible_manufacturers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Manufacturers eligible for this service",
                related_name="eligible_services",
                to="etop_backend.manufacturer",
            ),
        ),
    ]
